name: Deploy on merge

on:
  push:
    branches:
      - 'main'
      - 'staging'
      
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.10.0]
    steps:
    - uses: actions/checkout@v4
    
    - uses: pnpm/action-setup@v2
      with:
        version: "8.11.0"
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run Jest tests
      run: pnpm run test

    - name: Publish to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'