name: Node.js Jest

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**' 
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**' 
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.10.0]
    steps:
    - uses: actions/checkout@v4
    
    - uses: pnpm/action-setup@v2
      with:
        version: "8.11.0"
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run Jest tests
      run: pnpm run test